services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    # Pull models on startup
    entrypoint: >
      sh -c "
        ollama serve &
        sleep 5 &&
        ollama pull gemma3:1b &&
        ollama pull gpt-oss:20b &&
        wait
      "

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama

volumes:
  ollama-data: